/*
    Create user
*/

CREATE USER hoteluser WITH PASSWORD 'put password here';

/*
    Create tables and database
*/
Create database hotel owner hoteluser;

drop table if exists booking CASCADE;
drop table if exists booking_roomcategory CASCADE;
drop table if exists booking_services CASCADE;
drop table if exists guest CASCADE;
drop table if exists invoice CASCADE;
drop table if exists invoice_room_category_price_list CASCADE;
drop table if exists invoice_rooms CASCADE;
drop table if exists invoice_services CASCADE;
drop table if exists room CASCADE;
drop table if exists room_category CASCADE;
drop table if exists room_category_price CASCADE;
drop table if exists season CASCADE;
drop table if exists service CASCADE;
drop table if exists stay CASCADE;
drop table if exists stay_rooms CASCADE;

create table booking (
                         id bigint generated by default as identity,
                         checkin_date date,
                         checkout_date date,
                         is_active boolean,
                         amount_of_adults integer,
                         amount_of_children integer,
                         additional_information varchar(255),
                         booking_date date,
                         booking_number varchar(255),
                         domain_id varchar(255),
                         guest_id bigint not null,
                         primary key (id)
);

create table booking_roomcategory (
                                      booking_id bigint not null,
                                      room_category_id bigint not null,
                                      amount integer,
                                      primary key (booking_id, room_category_id)
);

create table booking_services (
                                  booking_id bigint,
                                  service_id bigint not null
);

create table guest (
                       id bigint generated by default as identity,
                       birth_date date,
                       phone_number varchar(255),
                       mail_address varchar(255),
                       discount_in_percent double precision,
                       gender integer,
                       domain_id varchar(255),
                       first_name varchar(255),
                       last_name varchar(255),
                       street_name varchar(255),
                       street_number varchar(255),
                       city varchar(255),
                       zip_code varchar(255),
                       country varchar(255),
                       primary key (id)
);

create table invoice (
                         id bigint generated by default as identity,
                         domain_id varchar(255),
                         invoice_number varchar(255),
                         invoice_date date,
                         amount_of_nights integer,
                         local_tax_per_person decimal(19,2),
                         local_tax_total decimal(19,2),
                         vat_in_percent decimal(19,2),
                         vat_in_euro decimal(19,2),
                         total_net_amount_before_discount decimal(19,2),
                         discount_in_percent decimal(19,2),
                         discount_in_euro decimal(19,2),
                         total_net_amount_after_local_tax decimal(19,2),
                         total_net_amount_after_discount decimal(19,2),
                         total_gross_amount decimal(19,2),
                         is_paid boolean,
                         stay_id bigint not null,
                         primary key (id)
);

create table invoice_room_category_price_list (
                                                  invoice_id bigint not null,
                                                  roomcategory_price_id bigint not null
);

create table invoice_rooms (
                               invoice_id bigint not null,
                               room_name bigint not null
);

create table invoice_services (
                                  invoice_id bigint,
                                  service_id bigint not null
);

create table room (
                      id bigint generated by default as identity,
                      room_name varchar(255),
                      status integer,
                      roomcategory_id bigint not null,
                      primary key (id)
);

create table room_category (
                               id bigint generated by default as identity,
                               domain_id varchar(255),
                               name varchar(255),
                               description text,
                               primary key (id)
);

create table room_category_price (
                                     id bigint generated by default as identity,
                                     domain_id varchar(255),
                                     season_id bigint not null,
                                     roomcategory_id bigint not null,
                                     price decimal(19,2),
                                     primary key (id)
);

create table season (
                        id bigint generated by default as identity,
                        start_date date,
                        end_date date,
                        domain_id varchar(255),
                        name varchar(255),
                        primary key (id)
);

create table service (
                         id bigint generated by default as identity,
                         domain_id varchar(255),
                         name varchar(255),
                         price decimal(19,2),
                         primary key (id)
);

create table stay (
                      id bigint generated by default as identity,
                      domain_id varchar(255),
                      booking_id bigint not null,
                      is_active boolean,
                      primary key (id)
);

create table stay_rooms (
                            stay_id bigint not null,
                            room_id bigint not null,
                            is_paid boolean,
                            primary key (stay_id, room_id)
);

/*
    Add constraints to tables
*/
alter table stay
    add constraint UK_ijkqrgpfljq9vk41gs6wss8ik unique (booking_id);

alter table booking
    add constraint FKjn3lsroa8t8h7x5sld9b0ru2u
        foreign key (guest_id)
            references guest;

alter table booking_roomcategory
    add constraint FKk6tccmr8ppp6l2g3595hchbep
        foreign key (booking_id)
            references booking;

alter table booking_roomcategory
    add constraint FK5f4o8cpk5gulhudxrov38blrv
        foreign key (room_category_id)
            references room_category;

alter table booking_services
    add constraint FK54clakuh2mj7p7p7bq6l7vy1o
        foreign key (service_id)
            references service;

alter table booking_services
    add constraint FK96s1e9neeevdkrc0uir5rbsgx
        foreign key (booking_id)
            references booking;

alter table invoice
    add constraint FKr6fioixy78vs9nee9qfmqhlu6
        foreign key (stay_id)
            references stay;

alter table invoice_room_category_price_list
    add constraint FKcil6auvle92rk95hab1dm04qf
        foreign key (roomcategory_price_id)
            references room_category_price;

alter table invoice_room_category_price_list
    add constraint FKgvstxuhn0vfjee1mfnmvppock
        foreign key (invoice_id)
            references invoice;

alter table invoice_rooms
    add constraint FK1jc14qvls5h2qwr77hwhbargg
        foreign key (room_name)
            references room;

alter table invoice_rooms
    add constraint FKkj6ndr4n9x2x290k1wlenlays
        foreign key (invoice_id)
            references invoice;

alter table invoice_services
    add constraint FKt6rmqin92xse8vt0i2fum293l
        foreign key (service_id)
            references service;

alter table invoice_services
    add constraint FKmt5ldof1ck4e5bi8eyln1fxy8
        foreign key (invoice_id)
            references invoice;

alter table room
    add constraint FKe8bbsy1yb92oos9e7lp1ay148
        foreign key (roomcategory_id)
            references room_category;

alter table room_category_price
    add constraint FK6fw08vjdrhlj6iyo21yq9o07p
        foreign key (season_id)
            references season;

alter table room_category_price
    add constraint FK1msxc31uv5yfceql19ak7q2dj
        foreign key (roomcategory_id)
            references room_category;

alter table stay
    add constraint FK3qg08nngxwx8b6vtkrn7nwfv
        foreign key (booking_id)
            references booking;

alter table stay_rooms
    add constraint FK9snn0m37tml2b413vb5qrb5fs
        foreign key (stay_id)
            references stay;

alter table stay_rooms
    add constraint FKr9axk4u8gokesav88b6dts2t9
        foreign key (room_id)
            references room;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO hoteluser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO hoteluser;